### PR TITLE
bang committ 2

### PR DESCRIPTION
**Pull request by Naveen010120**
commit is done

### CODE REVIEW

**Review by kondamahesh1250 — COMMENTED** [review]
ok

**Review by kondamahesh1250 — DISMISSED** [review]
ok

**Comment by kondamahesh1250** [comment]
ok

**Comment by Naveen010120** [comment]
done sir

**Review by Naveen010120 — COMMENTED** [review]
ok

**Review by kondamahesh1250 — COMMENTED** [review]
ok

**Review by kondamahesh1250 — APPROVED** [review]
ok

**Comment by kondamahesh1250** [comment]
ok

**Pull request closed without merging**
